version: "3.9"

services:
  app-dados:
    build:
      context: ./
      dockerfile: Dockerfile
    image: teste-dados-meteorologicos:v1
    container_name: app-dados
    ports:
      - 8888:8888
      - 3000-3005:3000-3005
    volumes:
      - "./:/home/jovyan/work"
